version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: llm-redis
    restart: always
    volumes:
      - ./redis_data:/data
    networks:
      - llm-network

  backend:
    image: crpi-mylnnkpla2o6c98d.cn-hangzhou.personal.cr.aliyuncs.com/rag-project-6/rag-project:latest # 替换成你的镜像地址
    container_name: llm-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./vector_db:/app/vector_db
      - ./logs:/app/logs
    env_file:
      - .env.prod
    depends_on:
      - redis
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge
